#!/bin/bash

flush="\e[0m"
black="\e[1;30m"
white="\e[1;37m"
yellow="\e[1;33m"

CNT=0

echo -e "\e[?7l"
echo -e " $flush$black         #####              $flush"
echo -e " $flush$black        #######             $flush"
echo -e " $flush$black        ##\e[1;37mO$flush$black#\e[1;37mO$flush$black##             $flush"
echo -e " $flush$black        #$flush$yellow#####$flush$black#             $flush"
echo -e " $flush$black      ##$flush$white##$flush$yellow###$flush$white##$flush$black##           $flush"
echo -e " $flush$black     #$flush$white##########$flush$black##          $flush"
echo -e " $flush$black    #$flush$white############$flush$black##         $flush"
echo -e " $flush$black    #$flush$white############$flush$black###        $flush"
echo -e " $flush$yellow ######$flush$black#$flush$white#######$flush$black#$flush$yellow######      $flush"
echo -e " $flush$yellow #######$flush$black#$flush$white#####$flush$black#$flush$yellow#######      $flush"
echo -e " $flush$yellow   #####$flush$black#######$flush$yellow#####        $flush"

echo -e "\e[13A"
echo -e "\e[28C$yellow $USER$flush $white$HOSTNAME"
echo -e "\e[28C$yellow OS:$flush $(cat /etc/os-release | grep PRETTY_NAME | cut -d "\"" -f 2)"
echo -e "\e[28C$yellow Kernel:$flush $(uname -r)"
echo -e "\e[28C$yellow Uptime:$flush $(uptime -p)"
echo -e "\e[28C$yellow Terminal:$flush $TERM"
echo -e "\e[28C$yellow WM:$flush $XDG_CURRENT_DESKTOP | $(xdpyinfo | awk '/dimensions/ {print $2}')"
(cat /proc/cpuinfo | grep "model name" | tail -n 1 | cut -d ":" -f 2) | while read -r i; do echo -e "\e[28C$yellow CPU:$flush $i"; done
(lspci | grep VGA | cut -d "[" -f 2 | cut -d "]" -f 1) | while read -r i; do echo -e "\e[28C$yellow GPU:$flush $i" ; done
echo -e "\e[28C$yellow Memory:$flush $(( $(free -m | tail -n 2 | head -n 1 | awk {'print $2'}) - $(free -m | tail -n 2 | head -n 1 | awk {'print $7'}) ))MiB / $(free -m | tail -n 2 | head -n 1 | awk {'print $2'})MiB"

echo -e "\e[28C$flush\e[0;1;34;94m┌───────────────\e[0;34m────────────────\e[0;37m──────────\e[0;1;30;90m┐$flush"
echo -e "\e[28C$flush\e[0;1;34;94m│Break \e[0;1;34;94mt\e[0;34mhe \e[0;34mrules; \e[0;34mFind \e[0;34my\e[0;37mour \e[0;37mfreedom! L\e[0;1;30;90mive \e[0;1;30;90m│$flush"
echo -e "\e[28C$flush\e[0;34m└───────────────\e[0;37m─────────────────\e[0;1;30;90m─────────┘$flush"
echo ""
#echo -e "\e[0B"
